// AUTHENTICATION
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILED = 'USER_FAILED'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_LOGOUT = 'USER_LOGOUT'

// QUESTIONS
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS'
export const QUESTION_FAILED = 'QUESTION_FAILED'
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING'
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED'
export const QUESTIONS_FAILED = 'QUESTIONS_FAILED'
export const QUESTION_REMOVED = 'QUESTION_REMOVED'

// SEARCH
export const USERS_FOUND = 'USERS_FOUND'
export const USERS_LOADING = 'USERS_LOADING'
export const USERS_CLEAR = 'USERS_CLEAR'

// PROFILE
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_LOADED = 'PROFILE_LOADED'

// ALERTS
export const SUCCESS_ALERT = 'SUCCESS_ALERT'
export const DANGER_ALERT = 'DANGER_ALERT'